# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Escuela\!Work\MP3vsWAV\mp3VSwav.ui'
#
# Created: Sun Aug 16 16:20:41 2015
#      by: PyQt4 UI code generator 4.9.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(833, 610)
        MainWindow.setMaximumSize(QtCore.QSize(840, 610))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_18 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.main_tab = QtGui.QWidget()
        self.main_tab.setObjectName(_fromUtf8("main_tab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.main_tab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem)
        self.label_20 = QtGui.QLabel(self.main_tab)
        self.label_20.setText(_fromUtf8(""))
        self.label_20.setPixmap(QtGui.QPixmap(_fromUtf8("data/images/imagesaaaaaaa.jpg")))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_19.addWidget(self.label_20)
        self.label_3 = QtGui.QLabel(self.main_tab)
        self.label_3.setMaximumSize(QtCore.QSize(1000, 170))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ravie"))
        font.setPointSize(40)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_19.addWidget(self.label_3)
        self.label_19 = QtGui.QLabel(self.main_tab)
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setPixmap(QtGui.QPixmap(_fromUtf8("data/images/images.jpg")))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_19.addWidget(self.label_19)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem1)
        self.gridLayout_10.addLayout(self.horizontalLayout_19, 0, 0, 1, 2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.start_btn = QtGui.QPushButton(self.main_tab)
        self.start_btn.setMinimumSize(QtCore.QSize(162, 30))
        self.start_btn.setMaximumSize(QtCore.QSize(172, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.start_btn.setFont(font)
        self.start_btn.setObjectName(_fromUtf8("start_btn"))
        self.verticalLayout_3.addWidget(self.start_btn)
        self.about_btn = QtGui.QPushButton(self.main_tab)
        self.about_btn.setMinimumSize(QtCore.QSize(50, 30))
        self.about_btn.setMaximumSize(QtCore.QSize(201, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.about_btn.setFont(font)
        self.about_btn.setObjectName(_fromUtf8("about_btn"))
        self.verticalLayout_3.addWidget(self.about_btn)
        self.research_btn = QtGui.QPushButton(self.main_tab)
        self.research_btn.setMinimumSize(QtCore.QSize(50, 30))
        self.research_btn.setMaximumSize(QtCore.QSize(231, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.research_btn.setFont(font)
        self.research_btn.setObjectName(_fromUtf8("research_btn"))
        self.verticalLayout_3.addWidget(self.research_btn)
        self.options_btn = QtGui.QPushButton(self.main_tab)
        self.options_btn.setMinimumSize(QtCore.QSize(50, 30))
        self.options_btn.setMaximumSize(QtCore.QSize(261, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.options_btn.setFont(font)
        self.options_btn.setObjectName(_fromUtf8("options_btn"))
        self.verticalLayout_3.addWidget(self.options_btn)
        self.players_btn = QtGui.QPushButton(self.main_tab)
        self.players_btn.setMinimumSize(QtCore.QSize(50, 30))
        self.players_btn.setMaximumSize(QtCore.QSize(291, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.players_btn.setFont(font)
        self.players_btn.setObjectName(_fromUtf8("players_btn"))
        self.verticalLayout_3.addWidget(self.players_btn)
        self.statics_btn = QtGui.QPushButton(self.main_tab)
        self.statics_btn.setMinimumSize(QtCore.QSize(50, 30))
        self.statics_btn.setMaximumSize(QtCore.QSize(321, 70))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.statics_btn.setFont(font)
        self.statics_btn.setObjectName(_fromUtf8("statics_btn"))
        self.verticalLayout_3.addWidget(self.statics_btn)
        self.gridLayout_10.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.welcome_lbl = QtGui.QLabel(self.main_tab)
        self.welcome_lbl.setMaximumSize(QtCore.QSize(1000, 170))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MoolBoran"))
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_lbl.setFont(font)
        self.welcome_lbl.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_lbl.setObjectName(_fromUtf8("welcome_lbl"))
        self.gridLayout_10.addWidget(self.welcome_lbl, 1, 1, 1, 1)
        self.tabWidget.addTab(self.main_tab, _fromUtf8(""))
        self.originalSignal_tab = QtGui.QWidget()
        self.originalSignal_tab.setObjectName(_fromUtf8("originalSignal_tab"))
        self.gridLayout = QtGui.QGridLayout(self.originalSignal_tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.originalSignal_tab)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.backOriginal_btn = QtGui.QPushButton(self.originalSignal_tab)
        self.backOriginal_btn.setMaximumSize(QtCore.QSize(100, 30))
        self.backOriginal_btn.setObjectName(_fromUtf8("backOriginal_btn"))
        self.horizontalLayout_2.addWidget(self.backOriginal_btn)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.endTestOrigianl_btn = QtGui.QPushButton(self.originalSignal_tab)
        self.endTestOrigianl_btn.setObjectName(_fromUtf8("endTestOrigianl_btn"))
        self.horizontalLayout_2.addWidget(self.endTestOrigianl_btn)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.start_btn_2 = QtGui.QPushButton(self.originalSignal_tab)
        self.start_btn_2.setMaximumSize(QtCore.QSize(100, 30))
        self.start_btn_2.setObjectName(_fromUtf8("start_btn_2"))
        self.horizontalLayout_2.addWidget(self.start_btn_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.originalSignal_tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_8.setMaximumSize(QtCore.QSize(310, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.originalPause_btn = QtGui.QPushButton(self.groupBox_8)
        self.originalPause_btn.setMinimumSize(QtCore.QSize(44, 0))
        self.originalPause_btn.setMaximumSize(QtCore.QSize(44, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.originalPause_btn.setFont(font)
        self.originalPause_btn.setObjectName(_fromUtf8("originalPause_btn"))
        self.gridLayout_4.addWidget(self.originalPause_btn, 0, 1, 1, 1)
        self.originalStop_btn = QtGui.QPushButton(self.groupBox_8)
        self.originalStop_btn.setMinimumSize(QtCore.QSize(43, 0))
        self.originalStop_btn.setMaximumSize(QtCore.QSize(43, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.originalStop_btn.setFont(font)
        self.originalStop_btn.setObjectName(_fromUtf8("originalStop_btn"))
        self.gridLayout_4.addWidget(self.originalStop_btn, 0, 2, 1, 1)
        self.originalPlay_btn = QtGui.QPushButton(self.groupBox_8)
        self.originalPlay_btn.setMinimumSize(QtCore.QSize(43, 0))
        self.originalPlay_btn.setMaximumSize(QtCore.QSize(43, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.originalPlay_btn.setFont(font)
        self.originalPlay_btn.setObjectName(_fromUtf8("originalPlay_btn"))
        self.gridLayout_4.addWidget(self.originalPlay_btn, 0, 0, 1, 1)
        self.horizontalSlider = QtGui.QSlider(self.groupBox_8)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName(_fromUtf8("horizontalSlider"))
        self.gridLayout_4.addWidget(self.horizontalSlider, 0, 5, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_8)
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setPixmap(QtGui.QPixmap(_fromUtf8("data/images/volumen.jpg")))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_4.addWidget(self.label_21, 0, 4, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 3, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_8, 3, 0, 1, 1)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(9)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.oscilogram_pw = OscillogramWidget(self.groupBox_9)
        self.oscilogram_pw.setObjectName(_fromUtf8("oscilogram_pw"))
        self.gridLayout_13.addWidget(self.oscilogram_pw, 0, 0, 1, 1)
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_9)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.spectogram_pw = SpectrogramWidget(self.groupBox_12)
        self.spectogram_pw.setObjectName(_fromUtf8("spectogram_pw"))
        self.gridLayout_14.addWidget(self.spectogram_pw, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.groupBox_12, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.originalSignal_tab, _fromUtf8(""))
        self.battle_tab = QtGui.QWidget()
        self.battle_tab.setObjectName(_fromUtf8("battle_tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.battle_tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.battle_tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.oscilogram1_pw = OscillogramWidget(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.oscilogram1_pw.setFont(font)
        self.oscilogram1_pw.setObjectName(_fromUtf8("oscilogram1_pw"))
        self.verticalLayout_2.addWidget(self.oscilogram1_pw)
        self.spectogram1_pw = SpectrogramWidget(self.groupBox_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spectogram1_pw.setFont(font)
        self.spectogram1_pw.setObjectName(_fromUtf8("spectogram1_pw"))
        self.verticalLayout_2.addWidget(self.spectogram1_pw)
        self.groupBox_11 = QtGui.QGroupBox(self.groupBox_3)
        self.groupBox_11.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setTitle(_fromUtf8(""))
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.pause1_btn = QtGui.QPushButton(self.groupBox_11)
        self.pause1_btn.setMinimumSize(QtCore.QSize(44, 0))
        self.pause1_btn.setMaximumSize(QtCore.QSize(44, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pause1_btn.setFont(font)
        self.pause1_btn.setObjectName(_fromUtf8("pause1_btn"))
        self.gridLayout_8.addWidget(self.pause1_btn, 0, 1, 1, 1)
        self.play1_btn = QtGui.QPushButton(self.groupBox_11)
        self.play1_btn.setMinimumSize(QtCore.QSize(43, 0))
        self.play1_btn.setMaximumSize(QtCore.QSize(43, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.play1_btn.setFont(font)
        self.play1_btn.setObjectName(_fromUtf8("play1_btn"))
        self.gridLayout_8.addWidget(self.play1_btn, 0, 0, 1, 1)
        self.stop1_btn = QtGui.QPushButton(self.groupBox_11)
        self.stop1_btn.setMinimumSize(QtCore.QSize(43, 0))
        self.stop1_btn.setMaximumSize(QtCore.QSize(43, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stop1_btn.setFont(font)
        self.stop1_btn.setObjectName(_fromUtf8("stop1_btn"))
        self.gridLayout_8.addWidget(self.stop1_btn, 0, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_11)
        self.label_24.setText(_fromUtf8(""))
        self.label_24.setPixmap(QtGui.QPixmap(_fromUtf8("data/images/volumen.jpg")))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_8.addWidget(self.label_24, 0, 4, 1, 1)
        self.horizontalSlider_2 = QtGui.QSlider(self.groupBox_11)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName(_fromUtf8("horizontalSlider_2"))
        self.gridLayout_8.addWidget(self.horizontalSlider_2, 0, 5, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 0, 3, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_11)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(self.battle_tab)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.oscilogram2_pw = OscillogramWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.oscilogram2_pw.setFont(font)
        self.oscilogram2_pw.setObjectName(_fromUtf8("oscilogram2_pw"))
        self.verticalLayout.addWidget(self.oscilogram2_pw)
        self.spectogram2_pw = SpectrogramWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spectogram2_pw.setFont(font)
        self.spectogram2_pw.setObjectName(_fromUtf8("spectogram2_pw"))
        self.verticalLayout.addWidget(self.spectogram2_pw)
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_10.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setTitle(_fromUtf8(""))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.stop2_btn = QtGui.QPushButton(self.groupBox_10)
        self.stop2_btn.setMinimumSize(QtCore.QSize(43, 0))
        self.stop2_btn.setMaximumSize(QtCore.QSize(43, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stop2_btn.setFont(font)
        self.stop2_btn.setObjectName(_fromUtf8("stop2_btn"))
        self.gridLayout_7.addWidget(self.stop2_btn, 0, 2, 1, 1)
        self.play2_btn = QtGui.QPushButton(self.groupBox_10)
        self.play2_btn.setMinimumSize(QtCore.QSize(43, 0))
        self.play2_btn.setMaximumSize(QtCore.QSize(43, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.play2_btn.setFont(font)
        self.play2_btn.setObjectName(_fromUtf8("play2_btn"))
        self.gridLayout_7.addWidget(self.play2_btn, 0, 0, 1, 1)
        self.pause2_btn = QtGui.QPushButton(self.groupBox_10)
        self.pause2_btn.setMinimumSize(QtCore.QSize(44, 0))
        self.pause2_btn.setMaximumSize(QtCore.QSize(44, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pause2_btn.setFont(font)
        self.pause2_btn.setObjectName(_fromUtf8("pause2_btn"))
        self.gridLayout_7.addWidget(self.pause2_btn, 0, 1, 1, 1)
        self.horizontalSlider_3 = QtGui.QSlider(self.groupBox_10)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName(_fromUtf8("horizontalSlider_3"))
        self.gridLayout_7.addWidget(self.horizontalSlider_3, 0, 5, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_10)
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setPixmap(QtGui.QPixmap(_fromUtf8("data/images/volumen.jpg")))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_7.addWidget(self.label_25, 0, 4, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem6, 0, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_10)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.select1_btn = QtGui.QPushButton(self.battle_tab)
        self.select1_btn.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.select1_btn.setFont(font)
        self.select1_btn.setObjectName(_fromUtf8("select1_btn"))
        self.horizontalLayout.addWidget(self.select1_btn)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem8)
        self.label = QtGui.QLabel(self.battle_tab)
        self.label.setMaximumSize(QtCore.QSize(500, 85))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ravie"))
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem9)
        self.select2_btn = QtGui.QPushButton(self.battle_tab)
        self.select2_btn.setMinimumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.select2_btn.setFont(font)
        self.select2_btn.setObjectName(_fromUtf8("select2_btn"))
        self.horizontalLayout.addWidget(self.select2_btn)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.battle_tab)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.next_btn = QtGui.QPushButton(self.battle_tab)
        self.next_btn.setMinimumSize(QtCore.QSize(150, 0))
        self.next_btn.setMaximumSize(QtCore.QSize(150, 30))
        self.next_btn.setObjectName(_fromUtf8("next_btn"))
        self.horizontalLayout_4.addWidget(self.next_btn)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.battle_tab, _fromUtf8(""))
        self.options_tab = QtGui.QWidget()
        self.options_tab.setObjectName(_fromUtf8("options_tab"))
        self.gridLayout_21 = QtGui.QGridLayout(self.options_tab)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.groupBox_4 = QtGui.QGroupBox(self.options_tab)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox_4.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.spinBox = QtGui.QSpinBox(self.groupBox_4)
        self.spinBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spinBox.setMinimum(1)
        self.spinBox.setMaximum(10000000)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_6.addWidget(self.spinBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        spacerItem13 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem13)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_9.addWidget(self.label_7)
        self.quality_cBox = QtGui.QComboBox(self.groupBox_4)
        self.quality_cBox.setMaximumSize(QtCore.QSize(95, 16777215))
        self.quality_cBox.setObjectName(_fromUtf8("quality_cBox"))
        self.quality_cBox.addItem(_fromUtf8(""))
        self.quality_cBox.addItem(_fromUtf8(""))
        self.quality_cBox.addItem(_fromUtf8(""))
        self.quality_cBox.addItem(_fromUtf8(""))
        self.quality_cBox.addItem(_fromUtf8(""))
        self.quality_cBox.addItem(_fromUtf8(""))
        self.quality_cBox.addItem(_fromUtf8(""))
        self.quality_cBox.addItem(_fromUtf8(""))
        self.quality_cBox.addItem(_fromUtf8(""))
        self.quality_cBox.addItem(_fromUtf8(""))
        self.horizontalLayout_9.addWidget(self.quality_cBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        spacerItem14 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem14)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_23 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(18)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_20.addWidget(self.label_23)
        self.toolButton = QtGui.QToolButton(self.groupBox_4)
        self.toolButton.setMinimumSize(QtCore.QSize(90, 0))
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_20.addWidget(self.toolButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        spacerItem15 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem15)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_26 = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(18)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_22.addWidget(self.label_26)
        self.addFiles_tb = QtGui.QToolButton(self.groupBox_4)
        self.addFiles_tb.setMinimumSize(QtCore.QSize(90, 0))
        self.addFiles_tb.setObjectName(_fromUtf8("addFiles_tb"))
        self.horizontalLayout_22.addWidget(self.addFiles_tb)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.verticalLayout_9.addLayout(self.verticalLayout_7)
        spacerItem16 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem16)
        self.groupBox_17 = QtGui.QGroupBox(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(18)
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.discreteRadioButton = QtGui.QRadioButton(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(18)
        self.discreteRadioButton.setFont(font)
        self.discreteRadioButton.setObjectName(_fromUtf8("discreteRadioButton"))
        self.horizontalLayout_29.addWidget(self.discreteRadioButton)
        self.discreteConfigureButton = QtGui.QPushButton(self.groupBox_17)
        self.discreteConfigureButton.setObjectName(_fromUtf8("discreteConfigureButton"))
        self.horizontalLayout_29.addWidget(self.discreteConfigureButton)
        self.horizontalLayout_29.setStretch(0, 3)
        self.horizontalLayout_29.setStretch(1, 2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.continuousRadioButton = QtGui.QRadioButton(self.groupBox_17)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(18)
        self.continuousRadioButton.setFont(font)
        self.continuousRadioButton.setChecked(True)
        self.continuousRadioButton.setObjectName(_fromUtf8("continuousRadioButton"))
        self.horizontalLayout_30.addWidget(self.continuousRadioButton)
        self.continuousConfigureButton = QtGui.QPushButton(self.groupBox_17)
        self.continuousConfigureButton.setObjectName(_fromUtf8("continuousConfigureButton"))
        self.horizontalLayout_30.addWidget(self.continuousConfigureButton)
        self.horizontalLayout_30.setStretch(0, 3)
        self.horizontalLayout_30.setStretch(1, 2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_30)
        self.verticalLayout_9.addWidget(self.groupBox_17)
        self.gridLayout_21.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_16 = QtGui.QGroupBox(self.options_tab)
        self.groupBox_16.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.audioFiles_listWidget = QtGui.QListWidget(self.groupBox_16)
        self.audioFiles_listWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.audioFiles_listWidget.setObjectName(_fromUtf8("audioFiles_listWidget"))
        self.gridLayout_20.addWidget(self.audioFiles_listWidget, 0, 0, 1, 1)
        self.gridLayout_21.addWidget(self.groupBox_16, 0, 1, 2, 1)
        self.label_22 = QtGui.QLabel(self.options_tab)
        self.label_22.setText(_fromUtf8(""))
        self.label_22.setPixmap(QtGui.QPixmap(_fromUtf8("data/images/Presentacion.jpg")))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_21.addWidget(self.label_22, 1, 0, 2, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.okOptions_btn = QtGui.QPushButton(self.options_tab)
        self.okOptions_btn.setMaximumSize(QtCore.QSize(100, 30))
        self.okOptions_btn.setObjectName(_fromUtf8("okOptions_btn"))
        self.horizontalLayout_5.addWidget(self.okOptions_btn)
        self.cancel_btn = QtGui.QPushButton(self.options_tab)
        self.cancel_btn.setMaximumSize(QtCore.QSize(100, 30))
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.horizontalLayout_5.addWidget(self.cancel_btn)
        self.gridLayout_21.addLayout(self.horizontalLayout_5, 2, 1, 1, 1)
        self.tabWidget.addTab(self.options_tab, _fromUtf8(""))
        self.statics_tab = QtGui.QWidget()
        self.statics_tab.setObjectName(_fromUtf8("statics_tab"))
        self.gridLayout_5 = QtGui.QGridLayout(self.statics_tab)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox_5 = QtGui.QGroupBox(self.statics_tab)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_10.addWidget(self.label_8)
        self.qualityStatics_cb = QtGui.QComboBox(self.groupBox_5)
        self.qualityStatics_cb.setMinimumSize(QtCore.QSize(130, 0))
        self.qualityStatics_cb.setObjectName(_fromUtf8("qualityStatics_cb"))
        self.qualityStatics_cb.addItem(_fromUtf8(""))
        self.qualityStatics_cb.addItem(_fromUtf8(""))
        self.qualityStatics_cb.addItem(_fromUtf8(""))
        self.qualityStatics_cb.addItem(_fromUtf8(""))
        self.qualityStatics_cb.addItem(_fromUtf8(""))
        self.qualityStatics_cb.addItem(_fromUtf8(""))
        self.qualityStatics_cb.addItem(_fromUtf8(""))
        self.qualityStatics_cb.addItem(_fromUtf8(""))
        self.qualityStatics_cb.addItem(_fromUtf8(""))
        self.qualityStatics_cb.addItem(_fromUtf8(""))
        self.horizontalLayout_10.addWidget(self.qualityStatics_cb)
        spacerItem17 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self.gridLayout_17.addLayout(self.horizontalLayout_10, 0, 0, 1, 2)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox_13 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_13 = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_15.addWidget(self.label_13)
        self.totalCountStatics_lbl = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.totalCountStatics_lbl.setFont(font)
        self.totalCountStatics_lbl.setObjectName(_fromUtf8("totalCountStatics_lbl"))
        self.horizontalLayout_15.addWidget(self.totalCountStatics_lbl)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_14 = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_16.addWidget(self.label_14)
        self.wavCountStatics_lbl = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.wavCountStatics_lbl.setFont(font)
        self.wavCountStatics_lbl.setObjectName(_fromUtf8("wavCountStatics_lbl"))
        self.horizontalLayout_16.addWidget(self.wavCountStatics_lbl)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_15 = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_17.addWidget(self.label_15)
        self.mp3CountStatics_lbl = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.mp3CountStatics_lbl.setFont(font)
        self.mp3CountStatics_lbl.setObjectName(_fromUtf8("mp3CountStatics_lbl"))
        self.horizontalLayout_17.addWidget(self.mp3CountStatics_lbl)
        self.verticalLayout_8.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_16 = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_18.addWidget(self.label_16)
        self.percentStatics_lbl = QtGui.QLabel(self.groupBox_13)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.percentStatics_lbl.setFont(font)
        self.percentStatics_lbl.setObjectName(_fromUtf8("percentStatics_lbl"))
        self.horizontalLayout_18.addWidget(self.percentStatics_lbl)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.gridLayout_15.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.label_33 = QtGui.QLabel(self.groupBox_13)
        self.label_33.setMaximumSize(QtCore.QSize(240, 150))
        self.label_33.setText(_fromUtf8(""))
        self.label_33.setPixmap(QtGui.QPixmap(_fromUtf8("data/images/Presentacion.jpg")))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_15.addWidget(self.label_33, 1, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_13)
        self.groupBox_14 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.gridLayout_16 = QtGui.QGridLayout(self.groupBox_14)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.totalStatics_pw = PlotWidget(self.groupBox_14)
        self.totalStatics_pw.setObjectName(_fromUtf8("totalStatics_pw"))
        self.gridLayout_16.addWidget(self.totalStatics_pw, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_14)
        self.gridLayout_17.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.backStatics_btn = QtGui.QPushButton(self.groupBox_5)
        self.backStatics_btn.setMaximumSize(QtCore.QSize(100, 30))
        self.backStatics_btn.setObjectName(_fromUtf8("backStatics_btn"))
        self.gridLayout_17.addWidget(self.backStatics_btn, 2, 1, 1, 1)
        self.playerStatics_lbl = QtGui.QLabel(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        self.playerStatics_lbl.setFont(font)
        self.playerStatics_lbl.setObjectName(_fromUtf8("playerStatics_lbl"))
        self.gridLayout_17.addWidget(self.playerStatics_lbl, 2, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.statics_tab, _fromUtf8(""))
        self.Research_tab = QtGui.QWidget()
        self.Research_tab.setObjectName(_fromUtf8("Research_tab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.Research_tab)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.researchPlainTextEdit = QtGui.QPlainTextEdit(self.Research_tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.researchPlainTextEdit.setFont(font)
        self.researchPlainTextEdit.setObjectName(_fromUtf8("researchPlainTextEdit"))
        self.verticalLayout_5.addWidget(self.researchPlainTextEdit)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_6 = QtGui.QLabel(self.Research_tab)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_7.addWidget(self.label_6)
        self.back_btn = QtGui.QPushButton(self.Research_tab)
        self.back_btn.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        self.back_btn.setFont(font)
        self.back_btn.setObjectName(_fromUtf8("back_btn"))
        self.horizontalLayout_7.addWidget(self.back_btn)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.Research_tab, _fromUtf8(""))
        self.about_tab = QtGui.QWidget()
        self.about_tab.setObjectName(_fromUtf8("about_tab"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.about_tab)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.aboutPlainTextEdit = QtGui.QPlainTextEdit(self.about_tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.aboutPlainTextEdit.setFont(font)
        self.aboutPlainTextEdit.setReadOnly(True)
        self.aboutPlainTextEdit.setObjectName(_fromUtf8("aboutPlainTextEdit"))
        self.verticalLayout_11.addWidget(self.aboutPlainTextEdit)
        spacerItem18 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem18)
        self.label_18 = QtGui.QLabel(self.about_tab)
        self.label_18.setText(_fromUtf8(""))
        self.label_18.setPixmap(QtGui.QPixmap(_fromUtf8("data/images/Presentación1.jpg")))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_11.addWidget(self.label_18)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_17 = QtGui.QLabel(self.about_tab)
        self.label_17.setText(_fromUtf8(""))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_21.addWidget(self.label_17)
        self.aboutBack_btn = QtGui.QPushButton(self.about_tab)
        self.aboutBack_btn.setMaximumSize(QtCore.QSize(160, 30))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        self.aboutBack_btn.setFont(font)
        self.aboutBack_btn.setObjectName(_fromUtf8("aboutBack_btn"))
        self.horizontalLayout_21.addWidget(self.aboutBack_btn)
        self.verticalLayout_11.addLayout(self.horizontalLayout_21)
        self.tabWidget.addTab(self.about_tab, _fromUtf8(""))
        self.end_tab = QtGui.QWidget()
        self.end_tab.setObjectName(_fromUtf8("end_tab"))
        self.gridLayout_11 = QtGui.QGridLayout(self.end_tab)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox_6 = QtGui.QGroupBox(self.end_tab)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_9 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_11.addWidget(self.label_9)
        self.totalCount_lbl = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.totalCount_lbl.setFont(font)
        self.totalCount_lbl.setObjectName(_fromUtf8("totalCount_lbl"))
        self.horizontalLayout_11.addWidget(self.totalCount_lbl)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_14.addWidget(self.label_12)
        self.wavCount_lbl = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.wavCount_lbl.setFont(font)
        self.wavCount_lbl.setObjectName(_fromUtf8("wavCount_lbl"))
        self.horizontalLayout_14.addWidget(self.wavCount_lbl)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_10 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_12.addWidget(self.label_10)
        self.mp3Count_lbl = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.mp3Count_lbl.setFont(font)
        self.mp3Count_lbl.setObjectName(_fromUtf8("mp3Count_lbl"))
        self.horizontalLayout_12.addWidget(self.mp3Count_lbl)
        self.verticalLayout_6.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_11 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_13.addWidget(self.label_11)
        self.percent_lbl = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.percent_lbl.setFont(font)
        self.percent_lbl.setObjectName(_fromUtf8("percent_lbl"))
        self.horizontalLayout_13.addWidget(self.percent_lbl)
        self.verticalLayout_6.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_32 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_28.addWidget(self.label_32)
        self.qualityResults_lbl = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(16)
        self.qualityResults_lbl.setFont(font)
        self.qualityResults_lbl.setObjectName(_fromUtf8("qualityResults_lbl"))
        self.horizontalLayout_28.addWidget(self.qualityResults_lbl)
        self.verticalLayout_6.addLayout(self.horizontalLayout_28)
        self.gridLayout_12.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.groupBox_6)
        self.label_31.setMaximumSize(QtCore.QSize(250, 130))
        self.label_31.setText(_fromUtf8(""))
        self.label_31.setPixmap(QtGui.QPixmap(_fromUtf8("data/images/Presentacion.jpg")))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_12.addWidget(self.label_31, 1, 0, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_6, 0, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.end_tab)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.total_pw = PlotWidget(self.groupBox_7)
        self.total_pw.setObjectName(_fromUtf8("total_pw"))
        self.gridLayout_9.addWidget(self.total_pw, 0, 0, 1, 1)

        # self.widget = FigureCanvasQTAgg(self.groupBox_7)
        # self.widget.setObjectName(_fromUtf8("widget"))
        # self.gridLayout_9.addWidget(self.widget, 1, 0, 1, 1)

        self.gridLayout_11.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.backEnd_btn = QtGui.QPushButton(self.end_tab)
        self.backEnd_btn.setMaximumSize(QtCore.QSize(100, 30))
        self.backEnd_btn.setObjectName(_fromUtf8("backEnd_btn"))
        self.gridLayout_11.addWidget(self.backEnd_btn, 1, 0, 1, 1)
        self.playerResults_lbl = QtGui.QLabel(self.end_tab)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(14)
        self.playerResults_lbl.setFont(font)
        self.playerResults_lbl.setObjectName(_fromUtf8("playerResults_lbl"))
        self.gridLayout_11.addWidget(self.playerResults_lbl, 1, 1, 1, 1)
        self.tabWidget.addTab(self.end_tab, _fromUtf8(""))
        self.player_tab = QtGui.QWidget()
        self.player_tab.setObjectName(_fromUtf8("player_tab"))
        self.gridLayout_19 = QtGui.QGridLayout(self.player_tab)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.groupBox_15 = QtGui.QGroupBox(self.player_tab)
        self.groupBox_15.setMaximumSize(QtCore.QSize(500, 16777215))
        self.groupBox_15.setTitle(_fromUtf8(""))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_28 = QtGui.QLabel(self.groupBox_15)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(18)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_24.addWidget(self.label_28)
        self.players_cBox = QtGui.QComboBox(self.groupBox_15)
        self.players_cBox.setMaximumSize(QtCore.QSize(300, 16777215))
        self.players_cBox.setObjectName(_fromUtf8("players_cBox"))
        self.horizontalLayout_24.addWidget(self.players_cBox)
        self.verticalLayout_10.addLayout(self.horizontalLayout_24)
        spacerItem19 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_10.addItem(spacerItem19)
        self.player_listWidget = QtGui.QListWidget(self.groupBox_15)
        self.player_listWidget.setObjectName(_fromUtf8("player_listWidget"))
        self.verticalLayout_10.addWidget(self.player_listWidget)
        spacerItem20 = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_10.addItem(spacerItem20)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.addPlayer_btn = QtGui.QPushButton(self.groupBox_15)
        self.addPlayer_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.addPlayer_btn.setObjectName(_fromUtf8("addPlayer_btn"))
        self.horizontalLayout_26.addWidget(self.addPlayer_btn)
        self.removePlayer_btn = QtGui.QPushButton(self.groupBox_15)
        self.removePlayer_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.removePlayer_btn.setObjectName(_fromUtf8("removePlayer_btn"))
        self.horizontalLayout_26.addWidget(self.removePlayer_btn)
        self.verticalLayout_10.addLayout(self.horizontalLayout_26)
        spacerItem21 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        self.verticalLayout_10.addItem(spacerItem21)
        self.gridLayout_19.addWidget(self.groupBox_15, 0, 0, 1, 1)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.addPlayer_GB = QtGui.QGroupBox(self.player_tab)
        self.addPlayer_GB.setMaximumSize(QtCore.QSize(400, 300))
        self.addPlayer_GB.setObjectName(_fromUtf8("addPlayer_GB"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.addPlayer_GB)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_29 = QtGui.QLabel(self.addPlayer_GB)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(18)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_25.addWidget(self.label_29)
        self.namePlayer_lineEdit = QtGui.QLineEdit(self.addPlayer_GB)
        self.namePlayer_lineEdit.setMaximumSize(QtCore.QSize(150, 16777215))
        self.namePlayer_lineEdit.setObjectName(_fromUtf8("namePlayer_lineEdit"))
        self.horizontalLayout_25.addWidget(self.namePlayer_lineEdit)
        self.verticalLayout_12.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.addNewPlayer_btn_2 = QtGui.QPushButton(self.addPlayer_GB)
        self.addNewPlayer_btn_2.setMaximumSize(QtCore.QSize(130, 16777215))
        self.addNewPlayer_btn_2.setObjectName(_fromUtf8("addNewPlayer_btn_2"))
        self.horizontalLayout_27.addWidget(self.addNewPlayer_btn_2)
        self.cancelAddPlayer_btn = QtGui.QPushButton(self.addPlayer_GB)
        self.cancelAddPlayer_btn.setMaximumSize(QtCore.QSize(130, 16777215))
        self.cancelAddPlayer_btn.setObjectName(_fromUtf8("cancelAddPlayer_btn"))
        self.horizontalLayout_27.addWidget(self.cancelAddPlayer_btn)
        self.verticalLayout_12.addLayout(self.horizontalLayout_27)
        self.verticalLayout_13.addWidget(self.addPlayer_GB)
        self.label_27 = QtGui.QLabel(self.player_tab)
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setPixmap(QtGui.QPixmap(_fromUtf8("data/images/Presentacion1.jpg")))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_13.addWidget(self.label_27)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_30 = QtGui.QLabel(self.player_tab)
        self.label_30.setText(_fromUtf8(""))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_23.addWidget(self.label_30)
        self.backPlayer_btn = QtGui.QPushButton(self.player_tab)
        self.backPlayer_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.backPlayer_btn.setObjectName(_fromUtf8("backPlayer_btn"))
        self.horizontalLayout_23.addWidget(self.backPlayer_btn)
        self.verticalLayout_13.addLayout(self.horizontalLayout_23)
        self.gridLayout_19.addLayout(self.verticalLayout_13, 0, 1, 1, 1)
        self.tabWidget.addTab(self.player_tab, _fromUtf8(""))
        self.gridLayout_18.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 833, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MP3 vs. WAV", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", " vs.", None, QtGui.QApplication.UnicodeUTF8))
        self.start_btn.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.about_btn.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.research_btn.setText(QtGui.QApplication.translate("MainWindow", "Research", None, QtGui.QApplication.UnicodeUTF8))
        self.options_btn.setText(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.players_btn.setText(QtGui.QApplication.translate("MainWindow", "Players", None, QtGui.QApplication.UnicodeUTF8))
        self.statics_btn.setText(QtGui.QApplication.translate("MainWindow", "Statics", None, QtGui.QApplication.UnicodeUTF8))
        self.welcome_lbl.setText(QtGui.QApplication.translate("MainWindow", "Welcome Ernesto !!!", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main_tab), QtGui.QApplication.translate("MainWindow", "Main Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.backOriginal_btn.setText(QtGui.QApplication.translate("MainWindow", "Main Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.endTestOrigianl_btn.setText(QtGui.QApplication.translate("MainWindow", "End Test", None, QtGui.QApplication.UnicodeUTF8))
        self.start_btn_2.setText(QtGui.QApplication.translate("MainWindow", "Start ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Original Signal WAV", None, QtGui.QApplication.UnicodeUTF8))
        self.originalPause_btn.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.originalStop_btn.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.originalPlay_btn.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Oscillogram", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("MainWindow", "Spectogram", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("MainWindow", "Signal 1", None, QtGui.QApplication.UnicodeUTF8))
        self.pause1_btn.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.play1_btn.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.stop1_btn.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Signal 2", None, QtGui.QApplication.UnicodeUTF8))
        self.stop2_btn.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.play2_btn.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.pause2_btn.setText(QtGui.QApplication.translate("MainWindow", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.select1_btn.setText(QtGui.QApplication.translate("MainWindow", "Select Signal 1", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "MP3", None, QtGui.QApplication.UnicodeUTF8))
        self.select2_btn.setText(QtGui.QApplication.translate("MainWindow", "Select Signal 2", None, QtGui.QApplication.UnicodeUTF8))
        self.next_btn.setText(QtGui.QApplication.translate("MainWindow", "Next Signal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Signals Count", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Quality Compression", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_cBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "1 (highest)", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_cBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_cBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_cBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_cBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_cBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_cBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_cBox.setItemText(7, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_cBox.setItemText(8, QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.quality_cBox.setItemText(9, QtGui.QApplication.translate("MainWindow", "10 (lowest)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Choose Files", None, QtGui.QApplication.UnicodeUTF8))
        self.toolButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Add Files", None, QtGui.QApplication.UnicodeUTF8))
        self.addFiles_tb.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_17.setTitle(QtGui.QApplication.translate("MainWindow", "Color Scale", None, QtGui.QApplication.UnicodeUTF8))
        self.discreteRadioButton.setText(QtGui.QApplication.translate("MainWindow", "Discrete", None, QtGui.QApplication.UnicodeUTF8))
        self.discreteConfigureButton.setText(QtGui.QApplication.translate("MainWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.continuousRadioButton.setText(QtGui.QApplication.translate("MainWindow", "Continuous", None, QtGui.QApplication.UnicodeUTF8))
        self.continuousConfigureButton.setText(QtGui.QApplication.translate("MainWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_16.setTitle(QtGui.QApplication.translate("MainWindow", "Audio Files", None, QtGui.QApplication.UnicodeUTF8))
        self.okOptions_btn.setText(QtGui.QApplication.translate("MainWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.cancel_btn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.options_tab), QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Quality Compression", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityStatics_cb.setItemText(0, QtGui.QApplication.translate("MainWindow", "1(highest)", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityStatics_cb.setItemText(1, QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityStatics_cb.setItemText(2, QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityStatics_cb.setItemText(3, QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityStatics_cb.setItemText(4, QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityStatics_cb.setItemText(5, QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityStatics_cb.setItemText(6, QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityStatics_cb.setItemText(7, QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityStatics_cb.setItemText(8, QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityStatics_cb.setItemText(9, QtGui.QApplication.translate("MainWindow", "10(lowest)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Total :", None, QtGui.QApplication.UnicodeUTF8))
        self.totalCountStatics_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Wright :", None, QtGui.QApplication.UnicodeUTF8))
        self.wavCountStatics_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Wrong :", None, QtGui.QApplication.UnicodeUTF8))
        self.mp3CountStatics_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Percent :", None, QtGui.QApplication.UnicodeUTF8))
        self.percentStatics_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_14.setTitle(QtGui.QApplication.translate("MainWindow", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.backStatics_btn.setText(QtGui.QApplication.translate("MainWindow", "Main Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.playerStatics_lbl.setText(QtGui.QApplication.translate("MainWindow", "Player:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.statics_tab), QtGui.QApplication.translate("MainWindow", "Statics", None, QtGui.QApplication.UnicodeUTF8))
        self.researchPlainTextEdit.setPlainText(QtGui.QApplication.translate("MainWindow", "\n"
"WAV (Waveform Audio File Format):\n"
"\n"
"Filename Extension: .wav\n"
"Format Type: Uncompressed\n"
"\n"
"WAV files are popular because they are considered a “first generation” format. That is, they are generally kept as the first digital copy of a file completely uncompressed. This means that WAV files are the best possible quality and have not gone through any digital alterations except to be outputted.\n"
"\n"
"The downside of this type of compression is large file sizes. If you download a song from Free Stock Music, you’ll notice the WAV files are substantially larger than the MP3 alternatives — sometimes by two to three times more!\n"
"\n"
"WAV files are good to have, however, because they allow the most flexibility. They are ideal for making copies of songs from because of their “first generation” status.\n"
"\n"
"\n"
"MP3 (MPEG-2 Audio Layer III):\n"
"\n"
"Filename Extension: .mp3\n"
"Format Type: Lossy Compressed\n"
"\n"
"When Internet file-sharing boomed into popularity with Napster and the iPod, the MP3 cornered the market for one reason: it had a small footprint. Without broadband connections, it was impractical at the time to share file sizes larger than the MP3 standard 2 – 3 Megabytes.\n"
"\n"
"And that preference has stuck for some time now even though MP3 does not have nearly the same amount of quality as WAV or AIFF files. But despite this growing base of people using higher quality formats, there are still those who prefer the MP3 – whether out of nostalgia or quality, who knows.\n"
"\n"
"What does this mean for you?  Well, the MP3 format uses compression which actually removes data from a song using complicated algorithms. The reason for removing this data is to save space and make the file smaller.\n"
"\n"
"MP3 Audio quality:\n"
"When performing lossy audio encoding, such as creating an MP3 file, there is a trade-off between the amount of space used and the sound quality of the result. Typically, the creator is allowed to set a bit rate, which specifies how many kilobits the file may use per second of audio. The higher the bit rate, the larger the compressed file will be, and, generally, the closer it will sound to the original file.\n"
"\n"
"With too low a bit rate, compression artifacts (i.e., sounds that were not present in the original recording) may be audible in the reproduction. Some audio is hard to compress because of its randomness and sharp attacks. When this type of audio is compressed, artifacts such as ringing or pre-echo are usually heard. A sample of applause compressed with a relatively low bit rate provides a good example of compression artifacts.\n"
"\n"
"Besides the bit rate of an encoded piece of audio, the quality of MP3 files also depends on the quality of the encoder itself, and the difficulty of the signal being encoded. As the MP3 standard allows quite a bit of freedom with encoding algorithms, different encoders may feature quite different quality, even with identical bit rates. As an example, in a public listening test featuring two different MP3 encoders at about 128 kbit/s, one scored 3.66 on a 1–5 scale, while the other scored only 2.22.\n"
"\n"
"Quality is dependent on the choice of encoder and encoding parameters.\n"
"\n"
"The simplest type of MP3 file uses one bit rate for the entire file – this is known as Constant Bit Rate (CBR) encoding. Using a constant bit rate makes encoding simpler and faster. However, it is also possible to create files where the bit rate changes throughout the file. These are known as Variable Bit Rate (VBR) files. The idea behind this is that, in any piece of audio, some parts will be much easier to compress, such as silence or music containing only a few instruments, while others will be more difficult to compress. So, the overall quality of the file may be increased by using a lower bit rate for the less complex passages and a higher one for the more complex parts. With some encoders, it is possible to specify a given quality, and the encoder will vary the bit rate accordingly. Users who know a particular \"quality setting\" that is transparent to their ears can use this value when encoding all of their music, and generally speaking not need to worry about performing personal listening tests on each piece of music to determine the correct bit rate.\n"
"\n"
"Perceived quality can be influenced by listening environment (ambient noise), listener attention, and listener training and in most cases by listener audio equipment (such as sound cards, speakers and headphones).\n"
"\n"
"A test given to new students by Stanford University Music Professor Jonathan Berger showed that student preference for MP3-quality music has risen each year. Berger said the students seem to prefer the \'sizzle\' sounds that MP3s bring to music.\n"
"\n"
"", None, QtGui.QApplication.UnicodeUTF8))
        self.back_btn.setText(QtGui.QApplication.translate("MainWindow", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Research_tab), QtGui.QApplication.translate("MainWindow", "Research", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutPlainTextEdit.setPlainText(QtGui.QApplication.translate("MainWindow", "Esta aplicacion esta pensada para realizar un estudio sobre las diferencias graficas entre las representaciones de una señal de audio en formato \".wav\" y formato \".mp3\", y condicho estudio se quiere lograr almacenar y procesar los datos recogidos para demostrar que tan evidentes son las diferencias entre dichos formatos asi como a que nivel de compresion son mas sensibles dichas diferencias.", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutBack_btn.setText(QtGui.QApplication.translate("MainWindow", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.about_tab), QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Total :", None, QtGui.QApplication.UnicodeUTF8))
        self.totalCount_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Wright:", None, QtGui.QApplication.UnicodeUTF8))
        self.wavCount_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Wrong:", None, QtGui.QApplication.UnicodeUTF8))
        self.mp3Count_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Percent:", None, QtGui.QApplication.UnicodeUTF8))
        self.percent_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("MainWindow", "Quality Compression:", None, QtGui.QApplication.UnicodeUTF8))
        self.qualityResults_lbl.setText(QtGui.QApplication.translate("MainWindow", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Graphics", None, QtGui.QApplication.UnicodeUTF8))
        self.backEnd_btn.setText(QtGui.QApplication.translate("MainWindow", "Main Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.playerResults_lbl.setText(QtGui.QApplication.translate("MainWindow", "Player:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.end_tab), QtGui.QApplication.translate("MainWindow", "Result", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Choose a Player", None, QtGui.QApplication.UnicodeUTF8))
        self.addPlayer_btn.setText(QtGui.QApplication.translate("MainWindow", "Add New Player", None, QtGui.QApplication.UnicodeUTF8))
        self.removePlayer_btn.setText(QtGui.QApplication.translate("MainWindow", "Remove Player", None, QtGui.QApplication.UnicodeUTF8))
        self.addPlayer_GB.setTitle(QtGui.QApplication.translate("MainWindow", "Editing New Player", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.addNewPlayer_btn_2.setText(QtGui.QApplication.translate("MainWindow", "Add Player", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelAddPlayer_btn.setText(QtGui.QApplication.translate("MainWindow", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.backPlayer_btn.setText(QtGui.QApplication.translate("MainWindow", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.player_tab), QtGui.QApplication.translate("MainWindow", "Player", None, QtGui.QApplication.UnicodeUTF8))

from duetto.widgets.OscillogramWidget import OscillogramWidget
from pyqtgraph import PlotWidget
from matplotlib.backends.backend_qt4agg import FigureCanvasQTAgg
from duetto.widgets.SpectrogramWidget import SpectrogramWidget
